package com.sisterhore;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.UnknownHostException;

import com.sisterhore.controller.Controller;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class AppGUI extends Application {

  private static final String MY_FIRST_JAVA_FX_APP = "CRDT Docs";

  @Override
  public void start(Stage primaryStage) throws Exception {
    primaryStage.setTitle(MY_FIRST_JAVA_FX_APP);

    FXMLLoader loader = new FXMLLoader();
    VBox vbox = FXMLLoader.load(getClass().getResource("/assets/example.fxml"));    

    Scene scene = new Scene(vbox);
    primaryStage.setScene(scene);
    primaryStage.setWidth(120.0);
    primaryStage.setHeight(120.0);
    primaryStage.show();
  }

  public static void main(String[] args) throws IOException, URISyntaxException {
    int port = args.length != 0 ? Integer.parseInt(args[0]) : 8887;
    Controller controller = null;
    try {
      controller = new Controller(port);
      launch(args);
    } catch (UnknownHostException e) {
      System.out.println("Exception occured: " + e);
      System.exit(1);
    }
  }

}
