
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.URISyntaxException;
import java.net.UnknownHostException;
import java.util.Scanner;

import CRDT.CRDT;
import Controller.Controller;

public class App {

    public static String getInput() {
        Scanner scan = new Scanner(System.in);
        String str = "";
        while(scan.hasNextLine()){
            str = scan.nextLine();
        }
        return str;
    }
    public static void main(String[] args) throws IOException, URISyntaxException {
        int port = args.length != 0 ? Integer.parseInt(args[0]) : 8887;
        Controller controller = null;
        CommandLineInterface cli = null;
        try {
            controller = new Controller(port);
            cli = new CommandLineInterface(controller);
            cli.start();
        } catch (UnknownHostException e) {
            System.out.println("Exception occured: " + e);
        }
    }
}
